# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CCChipmunk2D' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CCChipmunk2D
  pod 'CCChipmunk2D'

end

target 'CCChipmunk2DiOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CCChipmunk2DiOS
  pod 'CCChipmunk2D'

end
